---
- name: Configure Apache and Mariadb
  hosts: servera.lab.example.com
  remote_user: devops
  become: true
  become_method: sudo
  become_user: root
  tasks:
    - name: Installing database and web server
      ansible.builtin.dnf:
        name: 
          - httpd
          - mariadb-server
        state: present

    - name: Start and enable web server
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true


    - name: Start and enable the database
      ansible.builtin.service:
        name: mariadb
        state: started
        enabled: true

- name: Configure Firewall
  hosts: servera.lab.example.com
  tasks:
    - name: Installing Firewall
      ansible.builtin.dnf:
        name: firewalld
        state: present

    - name: Start and enable firewall
      ansible.builtin.service:
        name: firewalld
        state: started
        enabled: true

    - name: Open ports Apache
      ansible.posix.firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: yes


    - name: Open ports for MariaDB
      ansible.posix.firewalld:
        service: mysql
        permanent: true
        state: enabled
        immediate: yes
...

