---
- name: Setup Apache webserver
  hosts: servera.lab.example.com
  tasks:
    - name: Installing web server
      ansible.builtin.yum:
        name: httpd
        state: present

    - name: Start and enable the  web server
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true

    - name: Installing Firewall
      ansible.builtin.yum:
        name: firewalld
        state: latest
 
    - name: Start and enable firewall
      ansible.builtin.service:
        name: firewalld
        state: started
        enabled: true
 
    - name: Open ports Apache
      ansible.posix.firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: yes

    - name: Create a test page
      ansible.builtin.copy:
        content: "Welcome to servera intranet\n"
        dest: /var/www/html/index.html

- name: Testing the web Server
  hosts: localhost
  become: no

  tasks:
    - name: Checking for http connection
      ansible.builtin.uri:
        url: http://servera.lab.example.com
        status_code: 200
...

