---
- name: Decryption of ZIP file
  hosts: servera.lab.example.com
  no_log: yes
  tasks:
    - name: Include the encrypted variable file
      ansible.builtin.include_vars: secret.yml

    - name: copy the zip to managed hosts
      ansible.builtin.copy:
        src: ex.zip
        dest: /var/tmp/ex.zip

    - name: unzip the file with password from crypt.yml
      ansible.builtin.command:
        "unzip -o -P {{password}} /var/tmp/ex.zip -d /var/tmp"
      register: results

    - name: display
      ansible.builtin.debug:
        var: results
